Import des données et retraitement des données

In [ ]:


"#idée : backtester l'excel que j'ai envoyer en étant long et sinon hold 


import pandas as pd
import yfinance as yf

In [147]:
#Import des données qui proviennent du MMS 
df=pd.read_excel(r"C:\Users\malu\Documents\Recherche quant\usa_data.xlsx",header=0,skiprows=[1])
df

Unnamed: 0   CHOMAGE  Unnamed: 2 Unnamed: 3  BALANCE COMMERCIALE  \
0   2003-07-31  0.000000       0.063 2003-08-31             0.000000   
1   2003-08-31  0.041667       0.062 2003-09-30             0.000000   
2   2003-09-30  0.125000       0.061 2003-10-31             0.000000   
3   2003-10-31  0.166667       0.061 2003-11-30             0.000000   
4   2003-11-30  0.291667       0.060 2003-12-31             0.000000   
..         ...       ...         ...        ...                  ...   
260 2025-03-31  0.291667       0.041 2025-04-30             0.000000   
261 2025-04-30  0.000000       0.042 2025-05-31             0.000000   
262 2025-05-31  0.000000       0.042 2025-06-30             0.041667   
263 2025-06-30  0.000000       0.042 2025-07-31             0.083333   
264 2025-07-31  0.458333       0.041        NaT                  NaN   

     Unnamed: 5 Unnamed: 6  CONFIANCE CONSOMMATEUR  Unnamed: 8 Unnamed: 9  \
0      -472.425 2003-07-31                0.583333        89.7 2003-07-31   
1      -479.833 2003-08-31                0.666667        90.9 2003-08-31   
2      -483.340 2003-09-30                0.583333        89.3 2003-09-30   
3      -489.094 2003-10-31                0.500000        87.7 2003-10-31   
4      -495.387 2003-11-30                0.625000        89.6 2003-11-30   
..          ...        ...                     ...         ...        ...   
260   -1022.309 2025-03-31                0.250000        64.7 2025-03-31   
261   -1094.359 2025-04-30                0.000000        57.0 2025-04-30   
262   -1081.506 2025-05-31                0.000000        52.2 2025-05-31   
263   -1078.567 2025-06-30                0.000000        52.2 2025-06-30   
264         NaN 2025-07-31                0.125000        60.7 2025-07-31   

     ...  INDICATEUR AVANCE PIB  Unnamed: 17 Unnamed: 18       PMI  \
0    ...               0.666667        0.014  2003-07-31  0.583333   
1    ...               0.791667        0.024  2003-08-31  0.750000   
2    ...               0.791667        0.029  2003-09-30  0.958333   
3    ...               1.000000        0.044  2003-10-31  0.875000   
4    ...               1.000000        0.057  2003-11-30  1.000000   
..   ...                    ...          ...         ...       ...   
260  ...               0.958333       -0.030  2025-03-31  0.958333   
261  ...               0.833333       -0.035  2025-04-30  0.833333   
262  ...               0.750000       -0.043  2025-05-31  0.666667   
263  ...               0.750000       -0.040  2025-06-30  0.625000   
264  ...                    NaN          NaN  2025-07-31  0.833333   

     Unnamed: 20 Unnamed: 21  PRODUCTION INDUSTRIELLE  Unnamed: 23  \
0           49.0  2003-08-31                 0.500000      -0.0017   
1           51.0  2003-09-30                 0.500000       0.0038   
2           53.2  2003-10-31                 0.458333       0.0027   
3           52.4  2003-11-30                 0.541667       0.0082   
4           55.2  2003-12-31                 0.625000       0.0122   
..           ...         ...                      ...          ...   
260         50.3  2025-04-30                 0.958333       0.0124   
261         49.0  2025-05-31                 0.916667       0.0120   
262         48.7  2025-06-30                 1.000000       0.0143   
263         48.5  2025-07-31                 0.750000       0.0060   
264         49.0         NaT                      NaN          NaN   

    Unnamed: 24    MMS ECO  
0    2003-07-31  33.991228  
1    2003-08-31  50.000000  
2    2003-09-30  51.478495  
3    2003-10-31  52.419355  
4    2003-11-30  63.575269  
..          ...        ...  
260  2025-03-31  56.048387  
261  2025-04-30  39.650538  
262  2025-05-31  43.682796  
263  2025-06-30  49.731183  
264  2025-07-31  46.370968  

[265 rows x 26 columns]

In [148]:
df_chomage=df.iloc[:,0:3]
df_chomage

Unnamed: 0   CHOMAGE  Unnamed: 2
0   2003-07-31  0.000000       0.063
1   2003-08-31  0.041667       0.062
2   2003-09-30  0.125000       0.061
3   2003-10-31  0.166667       0.061
4   2003-11-30  0.291667       0.060
..         ...       ...         ...
260 2025-03-31  0.291667       0.041
261 2025-04-30  0.000000       0.042
262 2025-05-31  0.000000       0.042
263 2025-06-30  0.000000       0.042
264 2025-07-31  0.458333       0.041

[265 rows x 3 columns]

In [149]:
df_balance_co=df.iloc[:,3:6]
df_balance_co

Unnamed: 3  BALANCE COMMERCIALE  Unnamed: 5
0   2003-08-31             0.000000    -472.425
1   2003-09-30             0.000000    -479.833
2   2003-10-31             0.000000    -483.340
3   2003-11-30             0.000000    -489.094
4   2003-12-31             0.000000    -495.387
..         ...                  ...         ...
260 2025-04-30             0.000000   -1022.309
261 2025-05-31             0.000000   -1094.359
262 2025-06-30             0.041667   -1081.506
263 2025-07-31             0.083333   -1078.567
264        NaT                  NaN         NaN

[265 rows x 3 columns]

In [150]:
df_conf_conso=df.iloc[:,6:9]
df_conf_conso

Unnamed: 6  CONFIANCE CONSOMMATEUR  Unnamed: 8
0   2003-07-31                0.583333        89.7
1   2003-08-31                0.666667        90.9
2   2003-09-30                0.583333        89.3
3   2003-10-31                0.500000        87.7
4   2003-11-30                0.625000        89.6
..         ...                     ...         ...
260 2025-03-31                0.250000        64.7
261 2025-04-30                0.000000        57.0
262 2025-05-31                0.000000        52.2
263 2025-06-30                0.000000        52.2
264 2025-07-31                0.125000        60.7

[265 rows x 3 columns]

In [151]:
df_conf_eco=df.iloc[:,9:12]
df_conf_eco

Unnamed: 9  CONFIANCE ECO  Unnamed: 11
0   2003-07-31       0.125000         14.9
1   2003-08-31       0.375000         16.5
2   2003-09-30       0.250000         15.9
3   2003-10-31       0.416667         16.2
4   2003-11-30       0.583333         17.1
..         ...            ...          ...
260 2025-03-31       0.333333         19.1
261 2025-04-30       0.000000         18.3
262 2025-05-31       0.416667         19.2
263 2025-06-30       0.833333         21.4
264 2025-07-31       0.250000         19.0

[265 rows x 3 columns]

In [152]:
df_ventes_detail=df.iloc[:,12:15]
df_ventes_detail

Unnamed: 12  VENTES DE DETAIL  Unnamed: 14
0    2003-08-31          0.958333        0.047
1    2003-09-30          0.875000        0.042
2    2003-10-31          0.958333        0.048
3    2003-11-30          0.958333        0.064
4    2003-12-31          0.916667        0.054
..          ...               ...          ...
260  2025-04-30          0.791667        0.039
261  2025-05-31          0.958333        0.051
262  2025-06-30          0.916667        0.050
263  2025-07-31          0.583333        0.033
264         NaT               NaN          NaN

[265 rows x 3 columns]

In [153]:
df_pib=df.iloc[:,15:18]
df_pib

Unnamed: 15  INDICATEUR AVANCE PIB  Unnamed: 17
0    2003-08-31               0.666667        0.014
1    2003-09-30               0.791667        0.024
2    2003-10-31               0.791667        0.029
3    2003-11-30               1.000000        0.044
4    2003-12-31               1.000000        0.057
..          ...                    ...          ...
260  2025-04-30               0.958333       -0.030
261  2025-05-31               0.833333       -0.035
262  2025-06-30               0.750000       -0.043
263  2025-07-31               0.750000       -0.040
264         NaT                    NaN          NaN

[265 rows x 3 columns]

In [154]:
df_pmi=df.iloc[:,18:21]
df_pmi

Unnamed: 18       PMI  Unnamed: 20
0    2003-07-31  0.583333         49.0
1    2003-08-31  0.750000         51.0
2    2003-09-30  0.958333         53.2
3    2003-10-31  0.875000         52.4
4    2003-11-30  1.000000         55.2
..          ...       ...          ...
260  2025-03-31  0.958333         50.3
261  2025-04-30  0.833333         49.0
262  2025-05-31  0.666667         48.7
263  2025-06-30  0.625000         48.5
264  2025-07-31  0.833333         49.0

[265 rows x 3 columns]

In [155]:
df_prod_indu=df.iloc[:,21:24]
df_prod_indu

Unnamed: 21  PRODUCTION INDUSTRIELLE  Unnamed: 23
0    2003-08-31                 0.500000      -0.0017
1    2003-09-30                 0.500000       0.0038
2    2003-10-31                 0.458333       0.0027
3    2003-11-30                 0.541667       0.0082
4    2003-12-31                 0.625000       0.0122
..          ...                      ...          ...
260  2025-04-30                 0.958333       0.0124
261  2025-05-31                 0.916667       0.0120
262  2025-06-30                 1.000000       0.0143
263  2025-07-31                 0.750000       0.0060
264         NaT                      NaN          NaN

[265 rows x 3 columns]

In [156]:
df_mms=df.iloc[:,24:26]
df_mms

Unnamed: 24    MMS ECO
0    2003-07-31  33.991228
1    2003-08-31  50.000000
2    2003-09-30  51.478495
3    2003-10-31  52.419355
4    2003-11-30  63.575269
..          ...        ...
260  2025-03-31  56.048387
261  2025-04-30  39.650538
262  2025-05-31  43.682796
263  2025-06-30  49.731183
264  2025-07-31  46.370968

[265 rows x 2 columns]

In [157]:
df_pib
df_pib

Unnamed: 15  INDICATEUR AVANCE PIB  Unnamed: 17
0    2003-08-31               0.666667        0.014
1    2003-09-30               0.791667        0.024
2    2003-10-31               0.791667        0.029
3    2003-11-30               1.000000        0.044
4    2003-12-31               1.000000        0.057
..          ...                    ...          ...
260  2025-04-30               0.958333       -0.030
261  2025-05-31               0.833333       -0.035
262  2025-06-30               0.750000       -0.043
263  2025-07-31               0.750000       -0.040
264         NaT                    NaN          NaN

[265 rows x 3 columns]

In [158]:
liste_dfs = [df_chomage, df_balance_co, df_conf_conso, df_conf_eco, df_ventes_detail, df_pib, df_pmi, df_prod_indu]
liste_noms = ['chomage', 'balance_co', 'conf_conso', 'conf_eco', 'ventes_detail', 'pib', 'pmi', 'prod_indu']

for df, name in zip(liste_dfs, liste_noms):

    # Réinitialiser l’index
    df.reset_index(drop=True, inplace=True)

    # Renommer les colonnes comme demandé
    df.columns = [f'date_{name}', f'note_{name}', f'niveau_{name}']

    # Convertir la colonne date en datetime
    df[f'date_{name}'] = pd.to_datetime(df[f'date_{name}'], errors='coerce')

    # Formater en YYYY-MM
    df[f'date_{name}'] = df[f'date_{name}'].dt.strftime('%Y-%m')



In [159]:
for df, name in zip(liste_dfs, liste_noms):
    df.rename(columns={f'date_{name}': 'DATE'}, inplace=True)

# 2. Initialiser le DataFrame final avec le premier DataFrame de la liste
df_final = liste_dfs[0]

# 3. Faire un merge successif sur la colonne 'DATE'
for df in liste_dfs[1:]:
    df_final = df_final.merge(df, on='DATE', how='outer')

# 4. Trier par date
df_final = df_final.sort_values(by='DATE').reset_index(drop=True)

# 5. Optionnel : vérifier les résultats
df_final=df_final.dropna()
df_final

DATE  note_chomage  niveau_chomage  note_balance_co  \
1    2003-08      0.041667           0.062         0.000000   
2    2003-09      0.125000           0.061         0.000000   
3    2003-10      0.166667           0.061         0.000000   
4    2003-11      0.291667           0.060         0.000000   
5    2003-12      0.666667           0.058         0.000000   
..       ...           ...             ...              ...   
260  2025-03      0.291667           0.041         0.000000   
261  2025-04      0.000000           0.042         0.000000   
262  2025-05      0.000000           0.042         0.000000   
263  2025-06      0.000000           0.042         0.041667   
264  2025-07      0.458333           0.041         0.083333   

     niveau_balance_co  note_conf_conso  niveau_conf_conso  note_conf_eco  \
1             -472.425         0.666667               90.9       0.375000   
2             -479.833         0.583333               89.3       0.250000   
3             -483.340         0.500000               87.7       0.416667   
4             -489.094         0.625000               89.6       0.583333   
5             -495.387         0.916667               93.7       0.875000   
..                 ...              ...                ...            ...   
260           -966.729         0.250000               64.7       0.333333   
261          -1022.309         0.000000               57.0       0.000000   
262          -1094.359         0.000000               52.2       0.416667   
263          -1081.506         0.000000               52.2       0.833333   
264          -1078.567         0.125000               60.7       0.250000   

     niveau_conf_eco  note_ventes_detail  niveau_ventes_detail  note_pib  \
1               16.5            0.958333                 0.047  0.666667   
2               15.9            0.875000                 0.042  0.791667   
3               16.2            0.958333                 0.048  0.791667   
4               17.1            0.958333                 0.064  1.000000   
5               19.9            0.916667                 0.054  1.000000   
..               ...                 ...                   ...       ...   
260             19.1            0.875000                 0.046  1.000000   
261             18.3            0.791667                 0.039  0.958333   
262             19.2            0.958333                 0.051  0.833333   
263             21.4            0.916667                 0.050  0.750000   
264             19.0            0.583333                 0.033  0.750000   

     niveau_pib  note_pmi  niveau_pmi  note_prod_indu  niveau_prod_indu  
1         0.014  0.750000        51.0        0.500000           -0.0017  
2         0.024  0.958333        53.2        0.500000            0.0038  
3         0.029  0.875000        52.4        0.458333            0.0027  
4         0.044  1.000000        55.2        0.541667            0.0082  
5         0.057  1.000000        58.4        0.625000            0.0122  
..          ...       ...         ...             ...               ...  
260      -0.027  0.958333        50.3        0.958333            0.0143  
261      -0.030  0.833333        49.0        0.958333            0.0124  
262      -0.035  0.666667        48.7        0.916667            0.0120  
263      -0.043  0.625000        48.5        1.000000            0.0143  
264      -0.040  0.833333        49.0        0.750000            0.0060  

[263 rows x 17 columns]

In [160]:
import yfinance as yf
import pandas as pd

# Télécharger les données quotidiennes du S&P 500 (^GSPC)
sp500 = yf.download('^GSPC', start='1999-01-01', end='2025-08-01')

# Calculer la moyenne mensuelle
monthly_avg = sp500['Close'].resample('M').mean()

# Transformer en DataFrame propre
df_mensuel = monthly_avg.reset_index()
df_mensuel.columns = ['DATE', 'SPX_avg']

# Garder seulement janvier 1999 à juillet 2025
df_mensuel = df_mensuel[(df_mensuel['DATE'] >= '1999-01-01') & (df_mensuel['DATE'] <= '2025-07-31')]

df_mensuel


C:\Users\malu\AppData\Local\Temp\ipykernel_12940\3129928148.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  sp500 = yf.download('^GSPC', start='1999-01-01', end='2025-08-01')
[*********************100%***********************]  1 of 1 completed
C:\Users\malu\AppData\Local\Temp\ipykernel_12940\3129928148.py:8: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_avg = sp500['Close'].resample('M').mean()


DATE      SPX_avg
0   1999-01-31  1248.774735
1   1999-02-28  1246.582115
2   1999-03-31  1281.663914
3   1999-04-30  1334.756662
4   1999-05-31  1332.074011
..         ...          ...
314 2025-03-31  5683.983352
315 2025-04-30  5369.495722
316 2025-05-31  5810.919480
317 2025-06-30  6029.951514
318 2025-07-31  6249.069957

[319 rows x 2 columns]

In [161]:
df_mensuel['DATE'] = pd.to_datetime(df_mensuel['DATE'])
df_mensuel['DATE'] = df_mensuel['DATE'].dt.strftime('%Y-%m')
df_mensuel

DATE      SPX_avg
0    1999-01  1248.774735
1    1999-02  1246.582115
2    1999-03  1281.663914
3    1999-04  1334.756662
4    1999-05  1332.074011
..       ...          ...
314  2025-03  5683.983352
315  2025-04  5369.495722
316  2025-05  5810.919480
317  2025-06  6029.951514
318  2025-07  6249.069957

[319 rows x 2 columns]

In [162]:
df = df_final.merge(df_mensuel, on='DATE', how='left')
df=df.dropna()
df

DATE  note_chomage  niveau_chomage  note_balance_co  \
0    2003-08      0.041667           0.062         0.000000   
1    2003-09      0.125000           0.061         0.000000   
2    2003-10      0.166667           0.061         0.000000   
3    2003-11      0.291667           0.060         0.000000   
4    2003-12      0.666667           0.058         0.000000   
..       ...           ...             ...              ...   
258  2025-03      0.291667           0.041         0.000000   
259  2025-04      0.000000           0.042         0.000000   
260  2025-05      0.000000           0.042         0.000000   
261  2025-06      0.000000           0.042         0.041667   
262  2025-07      0.458333           0.041         0.083333   

     niveau_balance_co  note_conf_conso  niveau_conf_conso  note_conf_eco  \
0             -472.425         0.666667               90.9       0.375000   
1             -479.833         0.583333               89.3       0.250000   
2             -483.340         0.500000               87.7       0.416667   
3             -489.094         0.625000               89.6       0.583333   
4             -495.387         0.916667               93.7       0.875000   
..                 ...              ...                ...            ...   
258           -966.729         0.250000               64.7       0.333333   
259          -1022.309         0.000000               57.0       0.000000   
260          -1094.359         0.000000               52.2       0.416667   
261          -1081.506         0.000000               52.2       0.833333   
262          -1078.567         0.125000               60.7       0.250000   

     niveau_conf_eco  note_ventes_detail  niveau_ventes_detail  note_pib  \
0               16.5            0.958333                 0.047  0.666667   
1               15.9            0.875000                 0.042  0.791667   
2               16.2            0.958333                 0.048  0.791667   
3               17.1            0.958333                 0.064  1.000000   
4               19.9            0.916667                 0.054  1.000000   
..               ...                 ...                   ...       ...   
258             19.1            0.875000                 0.046  1.000000   
259             18.3            0.791667                 0.039  0.958333   
260             19.2            0.958333                 0.051  0.833333   
261             21.4            0.916667                 0.050  0.750000   
262             19.0            0.583333                 0.033  0.750000   

     niveau_pib  note_pmi  niveau_pmi  note_prod_indu  niveau_prod_indu  \
0         0.014  0.750000        51.0        0.500000           -0.0017   
1         0.024  0.958333        53.2        0.500000            0.0038   
2         0.029  0.875000        52.4        0.458333            0.0027   
3         0.044  1.000000        55.2        0.541667            0.0082   
4         0.057  1.000000        58.4        0.625000            0.0122   
..          ...       ...         ...             ...               ...   
258      -0.027  0.958333        50.3        0.958333            0.0143   
259      -0.030  0.833333        49.0        0.958333            0.0124   
260      -0.035  0.666667        48.7        0.916667            0.0120   
261      -0.043  0.625000        48.5        1.000000            0.0143   
262      -0.040  0.833333        49.0        0.750000            0.0060   

         SPX_avg  
0     989.531910  
1    1019.441900  
2    1038.734343  
3    1049.898945  
4    1080.635920  
..           ...  
258  5683.983352  
259  5369.495722  
260  5810.919480  
261  6029.951514  
262  6249.069957  

[263 rows x 18 columns]

In [163]:
df['SP_return']=df['SPX_avg'].pct_change()
df=df.dropna()
df

DATE  note_chomage  niveau_chomage  note_balance_co  \
1    2003-09      0.125000           0.061         0.000000   
2    2003-10      0.166667           0.061         0.000000   
3    2003-11      0.291667           0.060         0.000000   
4    2003-12      0.666667           0.058         0.000000   
5    2004-01      1.000000           0.057         0.000000   
..       ...           ...             ...              ...   
258  2025-03      0.291667           0.041         0.000000   
259  2025-04      0.000000           0.042         0.000000   
260  2025-05      0.000000           0.042         0.000000   
261  2025-06      0.000000           0.042         0.041667   
262  2025-07      0.458333           0.041         0.083333   

     niveau_balance_co  note_conf_conso  niveau_conf_conso  note_conf_eco  \
1             -479.833         0.583333               89.3       0.250000   
2             -483.340         0.500000               87.7       0.416667   
3             -489.094         0.625000               89.6       0.583333   
4             -495.387         0.916667               93.7       0.875000   
5             -495.770         0.791667               92.6       0.666667   
..                 ...              ...                ...            ...   
258           -966.729         0.250000               64.7       0.333333   
259          -1022.309         0.000000               57.0       0.000000   
260          -1094.359         0.000000               52.2       0.416667   
261          -1081.506         0.000000               52.2       0.833333   
262          -1078.567         0.125000               60.7       0.250000   

     niveau_conf_eco  note_ventes_detail  niveau_ventes_detail  note_pib  \
1               15.9            0.875000                 0.042  0.791667   
2               16.2            0.958333                 0.048  0.791667   
3               17.1            0.958333                 0.064  1.000000   
4               19.9            0.916667                 0.054  1.000000   
5               18.1            0.958333                 0.057  1.000000   
..               ...                 ...                   ...       ...   
258             19.1            0.875000                 0.046  1.000000   
259             18.3            0.791667                 0.039  0.958333   
260             19.2            0.958333                 0.051  0.833333   
261             21.4            0.916667                 0.050  0.750000   
262             19.0            0.583333                 0.033  0.750000   

     niveau_pib  note_pmi  niveau_pmi  note_prod_indu  niveau_prod_indu  \
1         0.024  0.958333        53.2        0.500000            0.0038   
2         0.029  0.875000        52.4        0.458333            0.0027   
3         0.044  1.000000        55.2        0.541667            0.0082   
4         0.057  1.000000        58.4        0.625000            0.0122   
5         0.063  1.000000        60.1        0.625000            0.0136   
..          ...       ...         ...             ...               ...   
258      -0.027  0.958333        50.3        0.958333            0.0143   
259      -0.030  0.833333        49.0        0.958333            0.0124   
260      -0.035  0.666667        48.7        0.916667            0.0120   
261      -0.043  0.625000        48.5        1.000000            0.0143   
262      -0.040  0.833333        49.0        0.750000            0.0060   

         SPX_avg  SP_return  
1    1019.441900   0.030226  
2    1038.734343   0.018925  
3    1049.898945   0.010748  
4    1080.635920   0.029276  
5    1132.517499   0.048010  
..           ...        ...  
258  5683.983352  -0.058739  
259  5369.495722  -0.055329  
260  5810.919480   0.082210  
261  6029.951514   0.037693  
262  6249.069957   0.036338  

[262 rows x 19 columns]

In [ ]:
# 2. Supprimer les NaN générés par pct_change
df = df.dropna(subset=['SP_return']).copy()

# 3. Définir les seuils de quantiles (1/3 et 2/3)
quantiles = df['SP_return'].quantile([1/3, 2/3]).values  # 33e et 66e percentiles

# 4. Fonction pour catégoriser en 3 classes
def categorize_return_3(x):
    if x < quantiles[0]:
        return 0  # baisse
    elif x < quantiles[1]:
        return 1  # neutre
    else:
        return 2  # hausse

# 5. Application
df['SP_return_cat_3'] = df['SP_return'].apply(categorize_return_3)

# Vérification
print(df[['SP_return', 'SP_return_cat_3']].head(10))


KeyError: "['SP_return_cat'] not in index"

In [168]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

# 1. Features (à ajuster si nécessaire)
features = [
    'note_chomage', 'niveau_chomage',
    'note_balance_co', 'niveau_balance_co',
    'note_conf_conso', 'niveau_conf_conso',
    'note_conf_eco', 'niveau_conf_eco',
    'note_ventes_detail', 'niveau_ventes_detail',
    'note_pib', 'niveau_pib',
    'note_pmi', 'niveau_pmi',
    'note_prod_indu', 'niveau_prod_indu'
]

# 2. Drop NaN et préparer X, y (avec la bonne cible à 3 classes)
df_ml = df.dropna(subset=features + ['SP_return_cat_3']).copy()
X = df_ml[features]
y = df_ml['SP_return_cat_3']

# 3. Split train/test (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4. Init et train modèle
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# 5. Prédictions
y_pred = clf.predict(X_test)

# 6. Évaluation
print("Classification report :\n", classification_report(y_test, y_pred))
print("Matrice de confusion :\n", confusion_matrix(y_test, y_pred))


Classification report :
               precision    recall  f1-score   support

           0       0.59      0.56      0.57        18
           1       0.53      0.53      0.53        17
           2       0.47      0.50      0.49        18

    accuracy                           0.53        53
   macro avg       0.53      0.53      0.53        53
weighted avg       0.53      0.53      0.53        53

Matrice de confusion :
 [[10  3  5]
 [ 3  9  5]
 [ 4  5  9]]


In [171]:


from xgboost import XGBClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

# 1. Features
features = [
    'note_chomage', 'niveau_chomage',
    'note_balance_co', 'niveau_balance_co',
    'note_conf_conso', 'niveau_conf_conso',
    'note_conf_eco', 'niveau_conf_eco',
    'note_ventes_detail', 'niveau_ventes_detail',
    'note_pib', 'niveau_pib',
    'note_pmi', 'niveau_pmi',
    'note_prod_indu', 'niveau_prod_indu'
]

# 2. Préparation des données
df_ml = df.dropna(subset=features + ['SP_return_cat_3']).copy()
X = df_ml[features]
y = df_ml['SP_return_cat_3']

# 3. Split train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# 4. Modèle XGBoost
xgb_model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=4,
    random_state=42,
    use_label_encoder=False,
    eval_metric='mlogloss'
)
xgb_model.fit(X_train, y_train)

# 5. Prédictions
y_pred = xgb_model.predict(X_test)

# 6. Évaluation
print("Classification report :\n", classification_report(y_test, y_pred))
print("Matrice de confusion :\n", confusion_matrix(y_test, y_pred))


Classification report :
               precision    recall  f1-score   support

           0       0.45      0.50      0.47        18
           1       0.44      0.41      0.42        17
           2       0.35      0.33      0.34        18

    accuracy                           0.42        53
   macro avg       0.41      0.42      0.41        53
weighted avg       0.41      0.42      0.41        53

Matrice de confusion :
 [[9 3 6]
 [5 7 5]
 [6 6 6]]


c:\Users\malu\AppData\Local\anaconda3\Lib\site-packages\xgboost\training.py:183: UserWarning: [14:04:46] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:738: 
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)
